spring.datasource.url=jdbc:postgresql://localhost:5432/rubi_db
spring.datasource.username=rubi_admin
spring.datasource.password=rubi_password_local
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
