spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rubi_db
    username: rubi_admin
    password: rubi_password_local
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
